language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
before_script:
  # Remove XDebug so composer runs faster
  - phpenv config-rm xdebug.ini
  - composer update --prefer-dist
  # Reconfigure XDebug so PHPUnit can create code coverage report (note: Xdebug can't be removed again now without rm-ing php.ini)
  - echo "extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script:
  - php ./vendor/phpunit/phpunit/phpunit --coverage-clover=build/logs/clover.xml
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="80b65a15a783f3ca91af2635f701052e94179ebf84aad0a031dcc90dddd30394" --format=php-clover  build/logs/clover.xml
after_success:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - travis_retry php coveralls.phar
notifications:
  email:
    - dev@dankempster.co.uk
branches:
  only:
    - develop
    - master
