language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
env:
  - DEPS=lowest
  - DEPS=stable
  - DEPS=dev

# Set up the project for testing
install:
  - if [[ $DEPS = 'lowest' ]]; then composer update -n --prefer-dist --prefer-lowest; fi
  - if [[ $DEPS = 'stable' ]]; then composer update -n --prefer-dist --prefer-stable; fi
  - if [[ $DEPS = 'dev' ]]; then composer update -n --prefer-dist; fi

# Run Tests
script:
  - php ./vendor/phpunit/phpunit/phpunit --coverage-clover=build/logs/clover.xml

# Process results
after_script:
  # Send code coverage to scrutinizer-ci.com & coveralls.io
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover  build/logs/clover.xml
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - travis_retry php coveralls.phar

# Build Matrix
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

branches:
  only:
    - develop
    - master
